/** @type implementation @purpose Provide the Cloudflare-hosted adjudication UI component. */

export const ADJUDICATION_CSS = `
:root{font:15px/1.45 system-ui,sans-serif;color:#172126;background:#f4f7f5}*{box-sizing:border-box}body{margin:0}header{padding:1rem 1.5rem;background:#fff;border-bottom:1px solid #ccd7d2;display:flex;align-items:center;gap:1rem;flex-wrap:wrap}h1{margin:0}header p{margin:0;color:#9e4128}button,input,textarea{font:inherit}button{padding:.55rem .8rem;border:0;border-radius:4px;background:#176e69;color:#fff;font-weight:700;cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}#login{max-width:38rem;margin:5rem auto;padding:2rem;background:#fff;border:1px solid #ccd7d2}#login input{width:100%;padding:.65rem;margin:.5rem 0}main{display:grid;grid-template-columns:18rem 1fr;min-height:calc(100vh - 74px)}aside{padding:1rem;border-right:1px solid #ccd7d2}.frame{display:block;width:100%;margin:.4rem 0;text-align:left;background:#d8e9e7;color:#174b48}.frame.resolved{background:#dce8d3}.workspace{padding:1.25rem}img{display:block;max-width:100%;max-height:42vh;margin:auto;background:#222}.columns{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.8rem;margin-top:1rem}article{padding:1rem;background:#fff;border:1px solid #ccd7d2}pre,textarea{width:100%;min-height:18rem;white-space:pre-wrap;font:12px/1.4 monospace}#message{color:#59666c}@media(max-width:900px){main,.columns{display:block}aside{border:0}.columns article{margin-top:.8rem}}
`;

export const ADJUDICATION_HTML = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Adjudicator C</title><link rel="stylesheet" href="/adjudication.css"></head><body>
<section id="login"><h1>Adjudicator C</h1><p>Open a review workspace.</p><label>Review ID<input id="review-id" autocomplete="off"></label><label>Access token<input id="token" type="password" autocomplete="current-password"></label><button id="open">Open review</button></section>
<div id="app" hidden><header><div><p>Cloudflare adjudication workspace</p><h1>Adjudicator C</h1></div><button id="complete">Complete adjudication</button><span id="message">Loading…</span></header><main><aside><h2>Disagreement frames</h2><div id="frames"></div></aside><section class="workspace"><h2 id="title">Select a frame</h2><img id="image" alt="Source evidence"><div class="columns"><article><h3>Reviewer A</h3><pre id="left"></pre><button id="use-a">Use A</button></article><article><h3>Reviewer B</h3><pre id="right"></pre><button id="use-b">Use B</button></article><article><h3>Merged decision</h3><textarea id="merged"></textarea><button id="save">Save edited decision</button></article></div></section></main></div><script type="module" src="/adjudication.js"></script></body></html>`;

export const ADJUDICATION_JS = `
const $=id=>document.getElementById(id);let state,selected,reviewId,token;
const keyOf=x=>x.source+'/'+x.filename;const frameOf=(payload,source,filename)=>payload.sources.find(x=>x.source===source).frames.find(x=>x.filename===filename);
const api=async(path,options={})=>{const response=await fetch('/api/reviews/'+encodeURIComponent(reviewId)+path,{...options,headers:{...options.headers,authorization:'Bearer '+token}});const body=await response.json();if(!response.ok)throw new Error(body.error||'Request failed');return body};
async function load(){state=await api('/state');render();}
function render(){const grouped=new Map();for(const item of state.comparison.disagreements)if(item.source&&item.filename)grouped.set(keyOf(item),item);const resolved=new Set(state.merged.review.adjudication_log.map(keyOf));$('frames').replaceChildren(...[...grouped.values()].map(item=>{const button=document.createElement('button');button.className='frame '+(resolved.has(keyOf(item))?'resolved':'');button.textContent=keyOf(item);button.onclick=()=>select(item);return button}));$('message').textContent=state.merged.review.adjudication_status==='complete'?'Complete — GET '+state.result_url:resolved.size+'/'+grouped.size+' disagreement frames resolved';$('complete').disabled=state.merged.review.adjudication_status==='complete'}
function select(item){selected=item;const {source,filename}=item;$('title').textContent=keyOf(item);$('image').src='/api/reviews/'+encodeURIComponent(reviewId)+'/frame?source='+encodeURIComponent(source)+'&filename='+encodeURIComponent(filename)+'&token='+encodeURIComponent(token);const left=frameOf(state.reviewer_a,source,filename),right=frameOf(state.reviewer_b,source,filename),merged=frameOf(state.merged,source,filename);$('left').textContent=JSON.stringify(left,null,2);$('right').textContent=JSON.stringify(right,null,2);$('merged').value=JSON.stringify(merged,null,2)}
async function resolve(frame,resolution){if(!selected)return;try{await api('/resolve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({source:selected.source,filename:selected.filename,frame,resolution})});await load();select(selected)}catch(error){alert(error.message)}}
$('open').onclick=async()=>{reviewId=$('review-id').value.trim();token=$('token').value;try{await load();$('login').hidden=true;$('app').hidden=false;history.replaceState({},'',location.pathname+'?review='+encodeURIComponent(reviewId))}catch(error){alert(error.message)}};
$('use-a').onclick=()=>selected&&resolve(frameOf(state.reviewer_a,selected.source,selected.filename),'reviewer_a');$('use-b').onclick=()=>selected&&resolve(frameOf(state.reviewer_b,selected.source,selected.filename),'reviewer_b');$('save').onclick=()=>{try{resolve(JSON.parse($('merged').value),'edited')}catch{alert('Merged decision must be valid JSON')}};
$('complete').onclick=async()=>{try{await api('/complete',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});await load()}catch(error){alert(error.message)}};$('review-id').value=new URLSearchParams(location.search).get('review')||'';
`;
